libarchive:
- '3.3'
# since we are linking with libc++ statically
# we need the SDK to be equal or newer than the one
# libc++ was built with
MACOSX_SDK_VERSION:  # [osx and x86_64]
- 10.14              # [osx and x86_64]
