{% set version = "0.6.1" %}

package:
  name: micromamba
  version: {{ version }}

source:
  - url: https://github.com/mamba-org/mamba/archive/{{ version }}.tar.gz
    sha256: 597d1a3dd3834678e292943672749b2e1ee40d32f6c4f4454ccc915699253d38
  - path: CLI11.hpp
    folder: include/mamba/CLI.hpp

build:
  number: 1
  ignore_run_exports:
    - libcurl        # [unix]
    - libarchive     # [unix]
    - libgcc-ng      # [linux]
    - libstdcxx-ng   # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - vcpkg  # [win]
  host:
    - cli11
    - cpp-filesystem
    - nlohmann_json
    - yaml-cpp-static    # [unix]
    - libcurl            # [unix]
    - libcurl-static     # [unix]
    - xz-static          # [unix]
    - libssh2-static     # [unix]
    - libarchive         # [unix]
    - krb5-static        # [unix]
    - libsolv-static     # [unix]
    - libopenssl-static  # [unix]
    - zstd-static        # [unix]
    - libnghttp2-static  # [unix]
    - lz4-c-static       # [unix]

test:
  commands:
    - test -f $PREFIX/bin/micromamba  # [unix]
    - micromamba --help
    - export MAMBA_ROOT_PREFIX=$PREFIX                                    # [unix]
    - micromamba create -p testenv -c conda-forge -c defaults python=3.9  # [unix]
    - testenv/bin/python --version                                        # [unix]
    - "testenv/bin/python -c 'import ssl'"                                # [unix]

    - "set MAMBA_ROOT_PREFIX=\"%PREFIX%\""                                # [win]
    - micromamba create -p testenv -c conda-forge -c defaults python=3.9  # [win]
    - testenv\\python.exe --version                                       # [win]
    - "testenv\\python.exe -c 'import ssl'"                               # [win]

about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - ZSTD_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - C_ARES_LICENSE.txt
    - LIBEV_LICENSE.txt
    - CPP_FILESYSTEM_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - mariusvniekerk
