{% set version = "0.4.0" %}
{% set sha256 = "2acf5046964184056f6e87b5dc5b57166f3d2da8be8c6a50bc9be56bced92398" %}

package:
  name: micromamba
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - placeholder.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - libcurl
    - libarchive

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - cli11
    - nlohmann_json
    # static libs
    - libcurl
    - libarchive
    - krb5-static
    - libsolv-static
    - libopenssl-static

test:
  commands:
    - test -f $PREFIX/bin/micromamba  # [unix]
    - micromamba --help

about:
  home: https://github.com/TheSnakePit/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/TheSnakePit/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
